name: Run tests

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@v5

    - name: Configure CMake
      run: >
        cmake -B ${{ matrix.build_type }}
        -G "Ninja"
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ matrix.build_type }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ matrix.build_type }}
      run: ctest --build-config ${{ matrix.build_type }}

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: ${{ matrix.os }}-${{ matrix.build_type }}
        path: ${{ matrix.build_type }}
